### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by hehehai** [maple3142/mergemp4#1]
不会用 - -。
视频，音频均下载到本地了，也选择了文件，但合成失败。
我没有下载ffmpeg

**Comment by maple3142** [comment]
有範例的影片與音樂文件嗎? 兩個都務必要是 `mp4` 才行

**Comment by hehehai** [comment]
ok，成功了！
下载下来的audio MP4文件格式后缀是 m4a 我改成 mp4 后可以了！
谢谢！

**Comment by Kissingbymodi** [comment]
点了generate为啥没反应不知道生成到哪了
