### ISSUE TITLE
页面奔溃

### ISSUE THREAD

**Issue by hehehai** [maple3142/mergemp4#2]
电脑内存8Gb，是不是内存小的原因？
![qq 20181030100231](https://user-images.githubusercontent.com/12692552/47690906-f01d7680-dc2a-11e8-8da7-495cf4f41136.png)
![qq 20181030100253](https://user-images.githubusercontent.com/12692552/47690914-fc093880-dc2a-11e8-83c7-f5c5e696175b.png)

**Comment by maple3142** [comment]
你是指 chrome 分頁掛掉？

**Comment by hehehai** [comment]
对，直接奔溃了

**Comment by maple3142** [comment]
這是 Chromium 的問題，firefox 應該就可以了
https://bugs.chromium.org/p/chromium/issues/detail?id=895153
