### ISSUE TITLE
直接clone的此repo打开index.html但是无法合成视频

### ISSUE THREAD

**Issue by Looong01** [maple3142/mergemp4#5]
直接clone的此repo打开index.html但是无法合成视频
审查元素报错：
![image](https://github.com/maple3142/mergemp4/assets/69568351/5c73e225-a13c-4b08-8440-6ff66cb39b74)

必须用node.js打包吗

**Comment by maple3142** [comment]
> 直接clone的此repo打开index.html但是无法合成视频 审查元素报错： ![image](https://user-images.githubusercontent.com/69568351/260087044-5c73e225-a13c-4b08-8440-6ff66cb39b74.png)
> 
> 必须用node.js打包吗

對
